### ISSUE TITLE
Add pages for Approach villages

### ISSUE THREAD

**Issue by clioweb** [rcmapp/CBW#13]

**Comment by clioweb** [comment]
@rcmapp Each of these will need some content.

**Comment by rcmapp** [comment]
Okay, I can do that. Would it be worth it for me to push a couple of other tasks off and work on this content this morning?

**Comment by clioweb** [comment]
@rcmapp Sorry, not necessarily. Just a note for us to keep this in mind that, for us to close this issue, we'll need to work on content at some point. I'm trying to just crank through the tickets I have, and make a better development environment on my local machine for CBW, than what I currently have.

**Comment by rcmapp** [comment]
Okay--I discussed this issue with AB and we decided it is worth pushing some other stuff off to establish some baseline content.  So I'll work on that for a couple of hours today.

**Comment by clioweb** [comment]
I've added these pages to the development svn repo.
