### ISSUE TITLE
Increase width of the home page.

### ISSUE THREAD

**Issue by clioweb** [rcmapp/CBW#9]

**Comment by clioweb** [comment]
@rcmapp Have updated the code to do this pretty flexibly. Now we'll need to discuss what to actually do with all this extra space.

**Comment by rcmapp** [comment]
I'll be available to discuss any time today. Let me know.

On Wednesday, May 18, 2016, Jeremy Boggs <notifications@github.com> wrote:

> @rcmapp <https://github.com/rcmapp> Have updated the code to do this
> pretty flexibly. Now we'll need to discuss what to actually do with all
> this extra space.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/rcmapp/CBW/issues/9#issuecomment-220012484>
>


-- 
Rennie Mapp
Project Manager, Collective Biographies of Women, IATH
Managing Editor, UVa Knowledge Base, SHANTI
University of Virginia
(717)713-1204
